MyUtils_DIR ?= $(CURDIR)
SIMULATION_DIR ?= $(MyUtils_DIR)/Simulation

PROJECT_DIR ?= $(CURDIR)
PROJECT_BUILD_DIR ?= $(PROJECT_DIR)/build
PROJECT_RTL_DIR ?= $(PROJECT_BUILD_DIR)/RTL

VERILOG_SOURCES := $(wildcard $(PROJECT_RTL_DIR)/*)

include $(SIMULATION_DIR)/simulation.mk
