IVERILOG_OUTPUT_DIR ?= $(PROJECT_DIR)/$(SIMULATOR)
IVERILOG_OUTPUT := $(IVERILOG_OUTPUT_DIR)/a.out

SIMULATOR_FLAGS = -W all -g2005-sv -I$(PROJECT_TESTBENCH_DIR) -I$(PROJECT_RTL_DIR)
ifeq ($(VCD),1)
SIMULATOR_FLAGS += -DVCD
endif

# Rule to create the directory if it doesn't exist
$(IVERILOG_OUTPUT_DIR):
	@mkdir -p $(IVERILOG_OUTPUT_DIR)

sim-run: $(IVERILOG_OUTPUT_DIR)
	iverilog -o $(IVERILOG_OUTPUT) $(SIMULATOR_FLAGS) $(VERILOG_SOURCES) $(SIMULATION_SOURCES)
	$(IVERILOG_OUTPUT)

sim-clean:
	-rm -rf $(IVERILOG_OUTPUT_DIR)

.PHONY: sim-run sim-clean